"""Add sizes and options model

Revision ID: 07ce45948c9f
Revises: 23348ea467a2
Create Date: 2025-11-12 10:30:14.355374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07ce45948c9f'
down_revision: Union[str, Sequence[str], None] = '23348ea467a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu_sizes', sa.Column('group', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('menu_sizes', 'group')
    # ### end Alembic commands ###
